"""
Dictionnaire des libellés officiels INSEE pour chaque code NAF.

Source: https://www.insee.fr/fr/information/2406147
Nomenclature d'activités française - NAF rév. 2

Usage:
    from foxreviews.subcategory.naf_libelles import get_naf_libelle, NAF_LIBELLES

    libelle = get_naf_libelle("43.22A")  # "Travaux d'installation d'eau et de gaz"
"""

# =============================================================================
# LIBELLÉS OFFICIELS NAF (nomenclature INSEE Rev. 2)
# =============================================================================

NAF_LIBELLES = {
    # SECTION A - AGRICULTURE, SYLVICULTURE ET PÊCHE
    "01.11Z": "Culture de céréales (à l'exception du riz), de légumineuses et de graines oléagineuses",
    "01.12Z": "Culture du riz",
    "01.13Z": "Culture de légumes, de melons, de racines et de tubercules",
    "01.14Z": "Culture de la canne à sucre",
    "01.15Z": "Culture du tabac",
    "01.16Z": "Culture de plantes à fibres",
    "01.19Z": "Autres cultures non permanentes",
    "01.21Z": "Culture de la vigne",
    "01.22Z": "Culture de fruits tropicaux et subtropicaux",
    "01.23Z": "Culture d'agrumes",
    "01.24Z": "Culture de fruits à pépins et à noyau",
    "01.25Z": "Culture d'autres fruits d'arbres ou d'arbustes et de fruits à coque",
    "01.26Z": "Culture de fruits oléagineux",
    "01.27Z": "Culture de plantes à boissons",
    "01.28Z": "Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques",
    "01.29Z": "Autres cultures permanentes",
    "01.30Z": "Reproduction de plantes",
    "01.41Z": "Élevage de vaches laitières",
    "01.42Z": "Élevage d'autres bovins et de buffles",
    "01.43Z": "Élevage de chevaux et d'autres équidés",
    "01.44Z": "Élevage de chameaux et d'autres camélidés",
    "01.45Z": "Élevage d'ovins et de caprins",
    "01.46Z": "Élevage de porcins",
    "01.47Z": "Élevage de volailles",
    "01.49Z": "Élevage d'autres animaux",
    "01.50Z": "Culture et élevage associés",
    "01.61Z": "Activités de soutien aux cultures",
    "01.62Z": "Activités de soutien à la production animale",
    "01.63Z": "Traitement primaire des récoltes",
    "01.64Z": "Traitement des semences",
    "01.70Z": "Chasse, piégeage et services annexes",
    "02.10Z": "Sylviculture et autres activités forestières",
    "02.20Z": "Exploitation forestière",
    "02.30Z": "Récolte de produits forestiers non ligneux poussant à l'état sauvage",
    "02.40Z": "Services de soutien à l'exploitation forestière",
    "03.11Z": "Pêche en mer",
    "03.12Z": "Pêche en eau douce",
    "03.21Z": "Aquaculture en mer",
    "03.22Z": "Aquaculture en eau douce",

    # SECTION B - INDUSTRIES EXTRACTIVES
    "05.10Z": "Extraction de houille",
    "05.20Z": "Extraction de lignite",
    "06.10Z": "Extraction de pétrole brut",
    "06.20Z": "Extraction de gaz naturel",
    "07.10Z": "Extraction de minerais de fer",
    "07.21Z": "Extraction de minerais d'uranium et de thorium",
    "07.29Z": "Extraction d'autres minerais de métaux non ferreux",
    "08.11Z": "Extraction de pierres ornementales et de construction",
    "08.12Z": "Exploitation de gravières et sablières, extraction d'argiles et de kaolin",
    "08.91Z": "Extraction des minéraux chimiques et d'engrais minéraux",
    "08.92Z": "Extraction de tourbe",
    "08.93Z": "Production de sel",
    "08.99Z": "Autres activités extractives n.c.a.",
    "09.10Z": "Activités de soutien à l'extraction d'hydrocarbures",
    "09.90Z": "Activités de soutien aux autres industries extractives",

    # SECTION C - INDUSTRIE MANUFACTURIÈRE
    "10.11Z": "Transformation et conservation de la viande de boucherie",
    "10.12Z": "Transformation et conservation de la viande de volaille",
    "10.13A": "Préparation industrielle de produits à base de viande",
    "10.13B": "Charcuterie",
    "10.20Z": "Transformation et conservation de poisson, de crustacés et de mollusques",
    "10.31Z": "Transformation et conservation de pommes de terre",
    "10.32Z": "Préparation de jus de fruits et légumes",
    "10.39A": "Autre transformation et conservation de légumes",
    "10.39B": "Transformation et conservation de fruits",
    "10.41A": "Fabrication d'huiles et graisses brutes",
    "10.41B": "Fabrication d'huiles et graisses raffinées",
    "10.42Z": "Fabrication de margarine et graisses comestibles similaires",
    "10.51A": "Fabrication de lait liquide et de produits frais",
    "10.51B": "Fabrication de beurre",
    "10.51C": "Fabrication de fromage",
    "10.51D": "Fabrication d'autres produits laitiers",
    "10.52Z": "Fabrication de glaces et sorbets",
    "10.61A": "Meunerie",
    "10.61B": "Autres activités du travail des grains",
    "10.62Z": "Fabrication de produits amylacés",
    "10.71A": "Fabrication industrielle de pain et de pâtisserie fraîche",
    "10.71B": "Cuisson de produits de boulangerie",
    "10.71C": "Boulangerie et boulangerie-pâtisserie",
    "10.71D": "Pâtisserie",
    "10.72Z": "Fabrication de biscuits, biscottes et pâtisseries de conservation",
    "10.73Z": "Fabrication de pâtes alimentaires",
    "10.81Z": "Fabrication de sucre",
    "10.82Z": "Fabrication de cacao, chocolat et de produits de confiserie",
    "10.83Z": "Transformation du thé et du café",
    "10.84Z": "Fabrication de condiments et assaisonnements",
    "10.85Z": "Fabrication de plats préparés",
    "10.86Z": "Fabrication d'aliments homogénéisés et diététiques",
    "10.89Z": "Fabrication d'autres produits alimentaires n.c.a.",
    "10.91Z": "Fabrication d'aliments pour animaux de ferme",
    "10.92Z": "Fabrication d'aliments pour animaux de compagnie",
    "11.01Z": "Production de boissons alcooliques distillées",
    "11.02A": "Fabrication de vins effervescents",
    "11.02B": "Vinification",
    "11.03Z": "Fabrication de cidre et de vins de fruits",
    "11.04Z": "Production d'autres boissons fermentées non distillées",
    "11.05Z": "Fabrication de bière",
    "11.06Z": "Fabrication de malt",
    "11.07A": "Industrie des eaux de table",
    "11.07B": "Production de boissons rafraîchissantes",

    # SECTION F - CONSTRUCTION
    "41.10A": "Promotion immobilière de logements",
    "41.10B": "Promotion immobilière de bureaux",
    "41.10C": "Promotion immobilière d'autres bâtiments",
    "41.10D": "Supports juridiques de programmes",
    "41.20A": "Construction de maisons individuelles",
    "41.20B": "Construction d'autres bâtiments",
    "42.11Z": "Construction de routes et autoroutes",
    "42.12Z": "Construction de voies ferrées de surface et souterraines",
    "42.13A": "Construction d'ouvrages d'art",
    "42.13B": "Construction et entretien de tunnels",
    "42.21Z": "Construction de réseaux pour fluides",
    "42.22Z": "Construction de réseaux électriques et de télécommunications",
    "42.91Z": "Construction d'ouvrages maritimes et fluviaux",
    "42.99Z": "Construction d'autres ouvrages de génie civil n.c.a.",
    "43.11Z": "Travaux de démolition",
    "43.12A": "Travaux de terrassement courants et travaux préparatoires",
    "43.12B": "Travaux de terrassement spécialisés ou de grande masse",
    "43.13Z": "Forages et sondages",
    "43.21A": "Travaux d'installation électrique dans tous locaux",
    "43.21B": "Travaux d'installation électrique sur la voie publique",
    "43.22A": "Travaux d'installation d'eau et de gaz en tous locaux",
    "43.22B": "Travaux d'installation d'équipements thermiques et de climatisation",
    "43.29A": "Travaux d'isolation",
    "43.29B": "Autres travaux d'installation n.c.a.",
    "43.31Z": "Travaux de plâtrerie",
    "43.32A": "Travaux de menuiserie bois et PVC",
    "43.32B": "Travaux de menuiserie métallique et serrurerie",
    "43.32C": "Agencement de lieux de vente",
    "43.33Z": "Travaux de revêtement des sols et des murs",
    "43.34Z": "Travaux de peinture et vitrerie",
    "43.39Z": "Autres travaux de finition",
    "43.91A": "Travaux de charpente",
    "43.91B": "Travaux de couverture par éléments",
    "43.99A": "Travaux d'étanchéification",
    "43.99B": "Travaux de montage de structures métalliques",
    "43.99C": "Travaux de maçonnerie générale et gros œuvre de bâtiment",
    "43.99D": "Autres travaux spécialisés de construction",
    "43.99E": "Location avec opérateur de matériel de construction",

    # SECTION G - COMMERCE
    "45.11Z": "Commerce de voitures et de véhicules automobiles légers",
    "45.19Z": "Commerce d'autres véhicules automobiles",
    "45.20A": "Entretien et réparation de véhicules automobiles légers",
    "45.20B": "Entretien et réparation d'autres véhicules automobiles",
    "45.31Z": "Commerce de gros d'équipements automobiles",
    "45.32Z": "Commerce de détail d'équipements automobiles",
    "45.40Z": "Commerce et réparation de motocycles",
    "46.11Z": "Intermédiaires du commerce en matières premières agricoles",
    "46.12A": "Centrales d'achat de carburant",
    "46.12B": "Autres intermédiaires du commerce en combustibles, métaux, minéraux",
    "46.13Z": "Intermédiaires du commerce en bois et matériaux de construction",
    "46.14Z": "Intermédiaires du commerce en machines, équipements industriels",
    "46.15Z": "Intermédiaires du commerce en meubles, articles de ménage",
    "46.16Z": "Intermédiaires du commerce en textiles, habillement, fourrures",
    "46.17A": "Centrales d'achat alimentaires",
    "46.17B": "Autres intermédiaires du commerce en denrées alimentaires",
    "46.18Z": "Intermédiaires spécialisés dans le commerce d'autres produits",
    "46.19A": "Centrales d'achat non alimentaires",
    "46.19B": "Autres intermédiaires du commerce en produits divers",
    "46.21Z": "Commerce de gros de céréales, de tabac non manufacturé",
    "46.22Z": "Commerce de gros de fleurs et plantes",
    "46.23Z": "Commerce de gros d'animaux vivants",
    "46.24Z": "Commerce de gros de cuirs et peaux",
    "46.31Z": "Commerce de gros de fruits et légumes",
    "46.32A": "Commerce de gros de viandes de boucherie",
    "46.32B": "Commerce de gros de produits à base de viande",
    "46.32C": "Commerce de gros de volailles et gibier",
    "46.33Z": "Commerce de gros de produits laitiers, œufs, huiles",
    "46.34Z": "Commerce de gros de boissons",
    "46.35Z": "Commerce de gros de produits à base de tabac",
    "46.36Z": "Commerce de gros de sucre, chocolat et confiserie",
    "46.37Z": "Commerce de gros de café, thé, cacao et épices",
    "46.38A": "Commerce de gros de poissons, crustacés et mollusques",
    "46.38B": "Commerce de gros alimentaire spécialisé divers",
    "46.39A": "Commerce de gros de produits surgelés",
    "46.39B": "Commerce de gros alimentaire non spécialisé",
    "46.41Z": "Commerce de gros de textiles",
    "46.42Z": "Commerce de gros d'habillement et de chaussures",
    "46.43Z": "Commerce de gros d'appareils électroménagers",
    "46.44Z": "Commerce de gros de vaisselle, verrerie et produits d'entretien",
    "46.45Z": "Commerce de gros de parfumerie et de produits de beauté",
    "46.46Z": "Commerce de gros de produits pharmaceutiques",
    "46.47Z": "Commerce de gros de meubles, de tapis et d'appareils d'éclairage",
    "46.48Z": "Commerce de gros d'articles d'horlogerie et de bijouterie",
    "46.49Z": "Commerce de gros d'autres biens domestiques",
    "46.51Z": "Commerce de gros d'ordinateurs et de logiciels",
    "46.52Z": "Commerce de gros de composants et d'équipements électroniques",
    "46.61Z": "Commerce de gros de matériel agricole",
    "46.62Z": "Commerce de gros de machines-outils",
    "46.63Z": "Commerce de gros de machines pour l'extraction, la construction",
    "46.64Z": "Commerce de gros de machines pour l'industrie textile",
    "46.65Z": "Commerce de gros de mobilier de bureau",
    "46.66Z": "Commerce de gros d'autres machines et équipements de bureau",
    "46.69A": "Commerce de gros de matériel électrique",
    "46.69B": "Commerce de gros de fournitures et équipements industriels divers",
    "46.69C": "Commerce de gros de fournitures et équipements divers",
    "46.71Z": "Commerce de gros de combustibles et de produits annexes",
    "46.72Z": "Commerce de gros de minerais et métaux",
    "46.73A": "Commerce de gros de bois et de matériaux de construction",
    "46.73B": "Commerce de gros d'appareils sanitaires",
    "46.74A": "Commerce de gros de quincaillerie",
    "46.74B": "Commerce de gros de fournitures pour la plomberie et le chauffage",
    "46.75Z": "Commerce de gros de produits chimiques",
    "46.76Z": "Commerce de gros d'autres produits intermédiaires",
    "46.77Z": "Commerce de gros de déchets et débris",
    "46.90Z": "Commerce de gros non spécialisé",
    "47.11A": "Commerce de détail de produits surgelés",
    "47.11B": "Commerce d'alimentation générale",
    "47.11C": "Supérettes",
    "47.11D": "Supermarchés",
    "47.11E": "Magasins multi-commerces",
    "47.11F": "Hypermarchés",
    "47.19A": "Grands magasins",
    "47.19B": "Autres commerces de détail en magasin non spécialisé",
    "47.21Z": "Commerce de détail de fruits et légumes en magasin spécialisé",
    "47.22Z": "Commerce de détail de viandes et de produits à base de viande",
    "47.23Z": "Commerce de détail de poissons, crustacés et mollusques",
    "47.24Z": "Commerce de détail de pain, pâtisserie et confiserie",
    "47.25Z": "Commerce de détail de boissons en magasin spécialisé",
    "47.26Z": "Commerce de détail de produits à base de tabac",
    "47.29Z": "Autres commerces de détail alimentaires en magasin spécialisé",

    # SECTION J - INFORMATION ET COMMUNICATION
    "58.11Z": "Édition de livres",
    "58.12Z": "Édition de répertoires et de fichiers d'adresses",
    "58.13Z": "Édition de journaux",
    "58.14Z": "Édition de revues et périodiques",
    "58.19Z": "Autres activités d'édition",
    "58.21Z": "Édition de jeux électroniques",
    "58.29A": "Édition de logiciels système et de réseau",
    "58.29B": "Édition de logiciels outils de développement et de langages",
    "58.29C": "Édition de logiciels applicatifs",
    "59.11A": "Production de films et de programmes pour la télévision",
    "59.11B": "Production de films institutionnels et publicitaires",
    "59.11C": "Production de films pour le cinéma",
    "59.12Z": "Post-production de films cinématographiques, de vidéo et de programmes",
    "59.13A": "Distribution de films cinématographiques",
    "59.13B": "Édition et distribution vidéo",
    "59.14Z": "Projection de films cinématographiques",
    "59.20Z": "Enregistrement sonore et édition musicale",
    "60.10Z": "Édition et diffusion de programmes radio",
    "60.20A": "Édition de chaînes généralistes",
    "60.20B": "Édition de chaînes thématiques",
    "61.10Z": "Télécommunications filaires",
    "61.20Z": "Télécommunications sans fil",
    "61.30Z": "Télécommunications par satellite",
    "61.90Z": "Autres activités de télécommunication",
    "62.01Z": "Programmation informatique",
    "62.02A": "Conseil en systèmes et logiciels informatiques",
    "62.02B": "Tierce maintenance de systèmes et d'applications informatiques",
    "62.03Z": "Gestion d'installations informatiques",
    "62.09Z": "Autres activités informatiques",
    "63.11Z": "Traitement de données, hébergement et activités connexes",
    "63.12Z": "Portails Internet",
    "63.91Z": "Activités des agences de presse",
    "63.99Z": "Autres services d'information n.c.a.",

    # SECTION M - ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES
    "69.10Z": "Activités juridiques",
    "69.20Z": "Activités comptables",
    "70.10Z": "Activités des sièges sociaux",
    "70.21Z": "Conseil en relations publiques et communication",
    "70.22Z": "Conseil pour les affaires et autres conseils de gestion",
    "71.11Z": "Activités d'architecture",
    "71.12A": "Activité des géomètres",
    "71.12B": "Ingénierie, études techniques",
    "71.20A": "Contrôle technique automobile",
    "71.20B": "Analyses, essais et inspections techniques",
    "72.11Z": "Recherche-développement en biotechnologie",
    "72.19Z": "Recherche-développement en autres sciences physiques et naturelles",
    "72.20Z": "Recherche-développement en sciences humaines et sociales",
    "73.11Z": "Activités des agences de publicité",
    "73.12Z": "Régie publicitaire de médias",
    "73.20Z": "Études de marché et sondages",
    "74.10Z": "Activités spécialisées de design",
    "74.20Z": "Activités photographiques",
    "74.30Z": "Traduction et interprétation",
    "74.90A": "Activité des économistes de la construction",
    "74.90B": "Activités spécialisées, scientifiques et techniques diverses",
    "75.00Z": "Activités vétérinaires",

    # SECTION N - ACTIVITÉS DE SERVICES ADMINISTRATIFS ET DE SOUTIEN
    "77.11A": "Location de courte durée de voitures et de véhicules automobiles légers",
    "77.11B": "Location de longue durée de voitures et de véhicules automobiles légers",
    "77.12Z": "Location et location-bail de camions",
    "77.21Z": "Location et location-bail d'articles de loisirs et de sport",
    "77.22Z": "Location de vidéocassettes et disques vidéo",
    "77.29Z": "Location et location-bail d'autres biens personnels et domestiques",
    "77.31Z": "Location et location-bail de machines et équipements agricoles",
    "77.32Z": "Location et location-bail de machines et équipements pour la construction",
    "77.33Z": "Location et location-bail de machines de bureau et de matériel informatique",
    "77.34Z": "Location et location-bail de matériels de transport par eau",
    "77.35Z": "Location et location-bail de matériels de transport aérien",
    "77.39Z": "Location et location-bail d'autres machines, équipements et biens matériels",
    "77.40Z": "Location-bail de propriété intellectuelle et de produits similaires",
    "78.10Z": "Activités des agences de placement de main-d'œuvre",
    "78.20Z": "Activités des agences de travail temporaire",
    "78.30Z": "Autre mise à disposition de ressources humaines",
    "79.11Z": "Activités des agences de voyage",
    "79.12Z": "Activités des voyagistes",
    "79.90Z": "Autres services de réservation et activités connexes",
    "80.10Z": "Activités de sécurité privée",
    "80.20Z": "Activités liées aux systèmes de sécurité",
    "80.30Z": "Activités d'enquête",
    "81.10Z": "Activités combinées de soutien lié aux bâtiments",
    "81.21Z": "Nettoyage courant des bâtiments",
    "81.22Z": "Autres activités de nettoyage des bâtiments et nettoyage industriel",
    "81.29A": "Désinfection, désinsectisation, dératisation",
    "81.29B": "Autres activités de nettoyage n.c.a.",
    "81.30Z": "Services d'aménagement paysager",
    "82.11Z": "Services administratifs combinés de bureau",
    "82.19Z": "Photocopie, préparation de documents et autres activités de bureau",
    "82.20Z": "Activités de centres d'appels",
    "82.30Z": "Organisation de foires, salons professionnels et congrès",
    "82.91Z": "Activités des agences de recouvrement de factures et des sociétés d'information financière",
    "82.92Z": "Activités de conditionnement",
    "82.99Z": "Autres activités de soutien aux entreprises n.c.a.",

    # SECTION Q - SANTÉ HUMAINE ET ACTION SOCIALE
    "86.10Z": "Activités hospitalières",
    "86.21Z": "Activités des médecins généralistes",
    "86.22A": "Activités de radiodiagnostic et de radiothérapie",
    "86.22B": "Activités chirurgicales",
    "86.22C": "Autres activités des médecins spécialistes",
    "86.23Z": "Pratique dentaire",
    "86.90A": "Ambulances",
    "86.90B": "Laboratoires d'analyses médicales",
    "86.90C": "Centres de collecte et banques d'organes",
    "86.90D": "Activités des infirmiers et des sages-femmes",
    "86.90E": "Activités des professionnels de la rééducation, de l'appareillage et des pédicures-podologues",
    "86.90F": "Activités de santé humaine non classées ailleurs",
    "87.10A": "Hébergement médicalisé pour personnes âgées",
    "87.10B": "Hébergement médicalisé pour enfants handicapés",
    "87.10C": "Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé",
    "87.20A": "Hébergement social pour handicapés mentaux et malades mentaux",
    "87.20B": "Hébergement social pour toxicomanes",
    "87.30A": "Hébergement social pour personnes âgées",
    "87.30B": "Hébergement social pour handicapés physiques",
    "87.90A": "Hébergement social pour enfants en difficultés",
    "87.90B": "Hébergement social pour adultes et familles en difficultés et autre hébergement social",
    "88.10A": "Aide à domicile",
    "88.10B": "Accueil ou accompagnement sans hébergement d'adultes handicapés ou de personnes âgées",
    "88.10C": "Aide par le travail",
    "88.91A": "Accueil de jeunes enfants",
    "88.91B": "Accueil ou accompagnement sans hébergement d'enfants handicapés",
    "88.99A": "Autre accueil ou accompagnement sans hébergement d'enfants et d'adolescents",
    "88.99B": "Action sociale sans hébergement n.c.a.",

    # SECTION S - AUTRES ACTIVITÉS DE SERVICES
    "94.11Z": "Activités des organisations patronales et consulaires",
    "94.12Z": "Activités des organisations professionnelles",
    "94.20Z": "Activités des syndicats de salariés",
    "94.91Z": "Activités des organisations religieuses",
    "94.92Z": "Activités des organisations politiques",
    "94.99Z": "Activités des organisations associatives n.c.a.",
    "95.11Z": "Réparation d'ordinateurs et d'équipements périphériques",
    "95.12Z": "Réparation d'équipements de communication",
    "95.21Z": "Réparation de produits électroniques grand public",
    "95.22Z": "Réparation d'appareils électroménagers et d'équipements pour la maison et le jardin",
    "95.23Z": "Réparation de chaussures et d'articles en cuir",
    "95.24Z": "Réparation de meubles et d'équipements du foyer",
    "95.25Z": "Réparation d'articles d'horlogerie et de bijouterie",
    "95.29Z": "Réparation d'autres biens personnels et domestiques",
    "96.01A": "Blanchisserie-teinturerie de gros",
    "96.01B": "Blanchisserie-teinturerie de détail",
    "96.02A": "Coiffure",
    "96.02B": "Soins de beauté",
    "96.03Z": "Services funéraires",
    "96.04Z": "Entretien corporel",
    "96.09Z": "Autres services personnels n.c.a.",
}


def get_naf_libelle(code: str) -> str | None:
    """
    Retourne le libellé officiel INSEE pour un code NAF.

    Args:
        code: Code NAF (ex: "43.22A", "62.01Z")

    Returns:
        Libellé officiel ou None si code inconnu
    """
    if not code:
        return None

    # Normaliser le code (majuscule, avec point)
    code = code.strip().upper()
    if len(code) == 5 and "." not in code:
        code = f"{code[:2]}.{code[2:]}"

    return NAF_LIBELLES.get(code)


def get_naf_libelle_or_default(code: str, default: str = "Activité non classée") -> str:
    """
    Retourne le libellé officiel INSEE ou une valeur par défaut.

    Args:
        code: Code NAF
        default: Valeur par défaut si code inconnu

    Returns:
        Libellé officiel ou default
    """
    return get_naf_libelle(code) or default
