# Generated by Django 5.2.8 on 2025-12-19 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SousCategorie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "texte_description_ia",
                    models.TextField(
                        blank=True,
                        help_text="Description complète générée par IA pour SEO",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Meta description SEO (160 caractères max)",
                        max_length=160,
                    ),
                ),
                (
                    "mots_cles",
                    models.TextField(
                        blank=True,
                        help_text="Mots-clés pour le moteur de recherche (séparés par des virgules)",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_categories",
                        to="category.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Catégorie",
                "verbose_name_plural": "Sous-Catégories",
                "ordering": ["ordre", "nom"],
                "unique_together": {("categorie", "nom")},
            },
        ),
    ]
