# Generated by Django 5.2.8 on 2025-12-22 13:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
        ("sponsorisation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe Customer ID (cus_xxx)",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Subscription ID (sub_xxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session ID (cs_xxx)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("past_due", "Impayé"),
                            ("canceled", "Annulé"),
                            ("incomplete", "Incomplet"),
                            ("incomplete_expired", "Incomplet expiré"),
                            ("trialing", "Période d'essai"),
                            ("unpaid", "Non payé"),
                        ],
                        db_index=True,
                        default="incomplete",
                        help_text="Statut de l'abonnement Stripe",
                        max_length=30,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Début de la période de facturation actuelle",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fin de la période de facturation actuelle",
                        null=True,
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Annulation programmée en fin de période",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'annulation de l'abonnement",
                        null=True,
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de fin effective de l'abonnement",
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=99.0,
                        help_text="Montant mensuel en euros",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="eur", help_text="Devise (ISO 4217)", max_length=3
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées supplémentaires",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        help_text="Entreprise abonnée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "pro_localisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="ProLocalisation sponsorisée (optionnel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="enterprise.prolocalisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur qui a créé l'abonnement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Invoice ID (in_xxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Payment Intent ID (pi_xxx)",
                        max_length=255,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Numéro de facture Stripe", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("open", "Ouverte"),
                            ("paid", "Payée"),
                            ("uncollectible", "Irrécouvrable"),
                            ("void", "Annulée"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Statut de la facture",
                        max_length=20,
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant dû en euros",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant payé en euros",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="eur", help_text="Devise (ISO 4217)", max_length=3
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(help_text="Début de la période facturée"),
                ),
                (
                    "period_end",
                    models.DateTimeField(help_text="Fin de la période facturée"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Date d'échéance", null=True
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de paiement", null=True
                    ),
                ),
                (
                    "invoice_pdf",
                    models.URLField(
                        blank=True, help_text="URL du PDF de la facture Stripe"
                    ),
                ),
                (
                    "hosted_invoice_url",
                    models.URLField(
                        blank=True, help_text="URL de la facture hébergée par Stripe"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées supplémentaires",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        help_text="Entreprise facturée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Abonnement associé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ViewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seo", "SEO / Organique"),
                            ("sponsorisation", "Sponsorisé"),
                            ("search", "Recherche interne"),
                            ("category", "Page catégorie"),
                            ("city", "Page ville"),
                            ("rotation", "Rotation sponsorisée"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Source de l'affichage",
                        max_length=20,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        blank=True,
                        help_text="Type de page (category, city, search, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, help_text="URL de la page source"),
                ),
                (
                    "position",
                    models.IntegerField(
                        blank=True,
                        help_text="Position dans la liste (1-5 pour sponsorisés)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User-Agent du navigateur"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP (anonymisée)", null=True
                    ),
                ),
                ("referrer", models.URLField(blank=True, help_text="URL du referrer")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de l'affichage",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées supplémentaires",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        help_text="Entreprise affichée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "pro_localisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="ProLocalisation affichée",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="enterprise.prolocalisation",
                    ),
                ),
                (
                    "sponsorisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sponsorisation associée (si affichage sponsorisé)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_events",
                        to="sponsorisation.sponsorisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement d'affichage",
                "verbose_name_plural": "Événements d'affichage",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seo", "SEO / Organique"),
                            ("sponsorisation", "Sponsorisé"),
                            ("search", "Recherche interne"),
                            ("category", "Page catégorie"),
                            ("city", "Page ville"),
                            ("direct", "Accès direct"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Source du clic",
                        max_length=20,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        blank=True,
                        help_text="Type de page (category, city, search, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, help_text="URL de la page source"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User-Agent du navigateur"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP (anonymisée)", null=True
                    ),
                ),
                ("referrer", models.URLField(blank=True, help_text="URL du referrer")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure du clic",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées supplémentaires",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        help_text="Entreprise cliquée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "pro_localisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="ProLocalisation cliquée",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="enterprise.prolocalisation",
                    ),
                ),
                (
                    "sponsorisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sponsorisation associée (si clic sponsorisé)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="click_events",
                        to="sponsorisation.sponsorisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de clic",
                "verbose_name_plural": "Événements de clic",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entreprise", "timestamp"],
                        name="billing_cli_entrepr_c0ed00_idx",
                    ),
                    models.Index(
                        fields=["pro_localisation", "timestamp"],
                        name="billing_cli_pro_loc_ff6aa1_idx",
                    ),
                    models.Index(
                        fields=["sponsorisation", "timestamp"],
                        name="billing_cli_sponsor_6899db_idx",
                    ),
                    models.Index(
                        fields=["source", "timestamp"],
                        name="billing_cli_source_e958e6_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="billing_cli_timesta_2a3fb2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["entreprise", "status"], name="billing_sub_entrepr_b405df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer_id"], name="billing_sub_stripe__97887e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="billing_sub_current_c59a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="billing_sub_status_684a21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["subscription", "status"], name="billing_inv_subscri_4c8e1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["entreprise", "status"], name="billing_inv_entrepr_644aba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="billing_inv_period__7aeaa2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="viewevent",
            index=models.Index(
                fields=["entreprise", "timestamp"],
                name="billing_vie_entrepr_5d0068_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="viewevent",
            index=models.Index(
                fields=["pro_localisation", "timestamp"],
                name="billing_vie_pro_loc_38b06e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="viewevent",
            index=models.Index(
                fields=["sponsorisation", "timestamp"],
                name="billing_vie_sponsor_c244be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="viewevent",
            index=models.Index(
                fields=["source", "timestamp"], name="billing_vie_source_1e9991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewevent",
            index=models.Index(
                fields=["timestamp"], name="billing_vie_timesta_6414f9_idx"
            ),
        ),
    ]
