# Generated by Django 5.2.8 on 2025-12-19 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisDecrypte",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texte_brut", models.TextField(help_text="Texte source de l'avis")),
                (
                    "texte_decrypte",
                    models.TextField(help_text="Texte décrypté par l'IA"),
                ),
                (
                    "source",
                    models.CharField(
                        default="google",
                        help_text="Source de l'avis (google, facebook, etc.)",
                        max_length=50,
                    ),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expiration de l'avis (régénération nécessaire)",
                        null=True,
                    ),
                ),
                (
                    "needs_regeneration",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="L'avis doit être régénéré",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0,
                        help_text="Score de confiance de l'IA (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis_decryptes",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "pro_localisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis_decryptes",
                        to="enterprise.prolocalisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis Décrypté",
                "verbose_name_plural": "Avis Décryptés",
                "ordering": ["-date_generation"],
                "indexes": [
                    models.Index(
                        fields=["entreprise", "pro_localisation"],
                        name="reviews_avi_entrepr_5c4bca_idx",
                    ),
                    models.Index(
                        fields=["needs_regeneration", "date_expiration"],
                        name="reviews_avi_needs_r_5c6a7f_idx",
                    ),
                    models.Index(
                        fields=["-date_generation"],
                        name="reviews_avi_date_ge_5cfb2f_idx",
                    ),
                ],
            },
        ),
    ]
