# Generated by Django 5.2.8 on 2025-12-25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avisdecrypte",
            name="ai_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Payload brut/normalisé renvoyé par l'IA (debug/traçabilité)",
            ),
        ),
        migrations.AddField(
            model_name="avisdecrypte",
            name="has_reviews",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si des avis publics existent pour cette ProLocalisation",
            ),
        ),
        migrations.AddField(
            model_name="avisdecrypte",
            name="job_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant job FastAPI (si applicable)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="avisdecrypte",
            name="review_rating",
            field=models.FloatField(
                blank=True,
                help_text="Note moyenne des avis sources (0-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="avisdecrypte",
            name="review_source",
            field=models.CharField(
                blank=True,
                help_text="Source des avis (ex: 'avis publics en ligne', 'google')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="avisdecrypte",
            name="texte_decrypte",
            field=models.TextField(
                blank=True,
                help_text="Texte décrypté par l'IA (null si aucun avis public exploitable)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="avisdecrypte",
            index=models.Index(
                fields=["pro_localisation", "has_reviews"],
                name="reviews_avi_pro_lo_2c7f3d_idx",
            ),
        ),
    ]
