# Generated by Django 5.2.8 on 2025-12-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_avisdecrypte_ai_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="avisdecrypte",
            name="review_count",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre d'avis sources (si fourni par l'IA)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
