# Generated by Django 5.2.8 on 2025-12-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_avisdecrypte_review_count"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="avisdecrypte",
            new_name="reviews_avi_pro_loc_88428c_idx",
            old_name="reviews_avi_pro_lo_2c7f3d_idx",
        ),
    ]
