# Generated by Django 5.2.8

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0006_prolocalisation_faq"),
        ("reviews", "0004_rename_reviews_avi_pro_lo_2c7f3d_idx_reviews_avi_pro_loc_88428c_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Titre de l'avis",
                        max_length=255,
                    ),
                ),
                (
                    "texte",
                    models.TextField(help_text="Contenu de l'avis"),
                ),
                (
                    "note",
                    models.IntegerField(
                        help_text="Note de 1 à 5 étoiles",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "date_avis",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date de l'avis",
                    ),
                ),
                (
                    "auteur_nom",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nom de l'auteur (vide = anonyme)",
                        max_length=100,
                    ),
                ),
                (
                    "auteur_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email de l'auteur (non affiché)",
                        max_length=254,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("client", "Créé par le client"),
                            ("google", "Importé de Google"),
                            ("facebook", "Importé de Facebook"),
                            ("site", "Déposé sur le site"),
                            ("import", "Importé (autre)"),
                        ],
                        default="client",
                        help_text="Source de l'avis",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente", "En attente de validation"),
                            ("en_cours_ia", "En cours de traitement IA"),
                            ("valide", "Validé"),
                            ("publie", "Publié"),
                            ("rejete", "Rejeté"),
                        ],
                        db_index=True,
                        default="en_attente",
                        help_text="Statut de l'avis",
                        max_length=20,
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de validation/rejet",
                        null=True,
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motif du rejet (si rejeté)",
                    ),
                ),
                (
                    "reponse_entreprise",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Réponse de l'entreprise à l'avis",
                    ),
                ),
                (
                    "date_reponse",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de la réponse",
                        null=True,
                    ),
                ),
                (
                    "masque",
                    models.BooleanField(
                        default=False,
                        help_text="Avis masqué (non affiché publiquement)",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = automatique)",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "pro_localisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="enterprise.prolocalisation",
                    ),
                ),
                (
                    "avis_decrypte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avis décrypté généré par l'IA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avis_sources",
                        to="reviews.avisdecrypte",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant validé/rejeté",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avis_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "ordering": ["-date_avis", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entreprise", "statut"],
                        name="reviews_avi_entrepr_avis_idx",
                    ),
                    models.Index(
                        fields=["pro_localisation", "statut"],
                        name="reviews_avi_pro_loc_avis_idx",
                    ),
                    models.Index(
                        fields=["statut", "-date_avis"],
                        name="reviews_avi_statut_date_idx",
                    ),
                    models.Index(
                        fields=["-date_avis"],
                        name="reviews_avi_date_av_idx",
                    ),
                ],
            },
        ),
    ]
