# Generated by Django 5.2.8 on 2025-12-19 08:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
        ("userprofile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="entreprise",
            field=models.ForeignKey(
                blank=True,
                help_text="Entreprise liée au client (optionnel).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="enterprise.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Numéro de téléphone au format international.",
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("client", "Client"),
                ],
                db_index=True,
                default="client",
                help_text="Rôle de l'utilisateur dans le système FOX-Reviews.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="userprofile_role_a718ae_idx"),
        ),
    ]
