# Generated by Django 5.2.8 on 2025-12-19 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
        ("subcategory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "siren",
                    models.CharField(
                        db_index=True,
                        help_text="Numéro SIREN (9 chiffres)",
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Numéro SIRET (14 chiffres)",
                        max_length=14,
                        null=True,
                    ),
                ),
                ("nom", models.CharField(db_index=True, max_length=255)),
                (
                    "nom_commercial",
                    models.CharField(
                        blank=True,
                        help_text="Nom commercial si différent du nom légal",
                        max_length=255,
                    ),
                ),
                ("adresse", models.TextField()),
                ("code_postal", models.CharField(db_index=True, max_length=5)),
                ("ville_nom", models.CharField(db_index=True, max_length=100)),
                (
                    "naf_code",
                    models.CharField(
                        db_index=True, help_text="Code NAF/APE", max_length=6
                    ),
                ),
                (
                    "naf_libelle",
                    models.CharField(help_text="Libellé du code NAF", max_length=255),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email_contact", models.EmailField(blank=True, max_length=254)),
                ("site_web", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Entreprise active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(
                        fields=["siren", "is_active"],
                        name="enterprise__siren_cfe96a_idx",
                    ),
                    models.Index(
                        fields=["ville_nom", "code_postal"],
                        name="enterprise__ville_n_8e7429_idx",
                    ),
                    models.Index(
                        fields=["naf_code"], name="enterprise__naf_cod_9153d3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProLocalisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone_description",
                    models.TextField(
                        blank=True, help_text="Description de la zone d'intervention"
                    ),
                ),
                (
                    "texte_long_entreprise",
                    models.TextField(
                        blank=True,
                        help_text="Texte long (2 pages) généré par IA pour la fiche entreprise",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Meta description SEO (160 caractères max)",
                        max_length=160,
                    ),
                ),
                (
                    "date_derniere_generation_ia",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de la dernière génération IA du contenu",
                        null=True,
                    ),
                ),
                (
                    "note_moyenne",
                    models.FloatField(
                        default=0,
                        help_text="Note moyenne calculée",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "nb_avis",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre d'avis",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "score_global",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Score global calculé (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="ProLocalisation vérifiée par un admin"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="ProLocalisation active"
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_localisations",
                        to="enterprise.entreprise",
                    ),
                ),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_localisations",
                        to="subcategory.souscategorie",
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_localisations",
                        to="location.ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pro-Localisation",
                "verbose_name_plural": "Pro-Localisations",
                "ordering": ["-score_global", "-note_moyenne"],
                "indexes": [
                    models.Index(
                        fields=["entreprise", "sous_categorie", "ville"],
                        name="enterprise__entrepr_e8c804_idx",
                    ),
                    models.Index(
                        fields=["score_global", "note_moyenne"],
                        name="enterprise__score_g_743bf6_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="enterprise__is_acti_9b3eee_idx",
                    ),
                ],
                "unique_together": {("entreprise", "sous_categorie", "ville")},
            },
        ),
    ]
