# Generated by Django 5.2.8 on 2025-12-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="contacts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Données de contact supplémentaires (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="domain",
            field=models.CharField(
                blank=True, help_text="Nom de domaine (ex: exemple.fr)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="google_place_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="Google Place ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude GPS",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="logo",
            field=models.URLField(blank=True, help_text="URL du logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude GPS",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="main_image",
            field=models.URLField(blank=True, help_text="URL de l'image principale"),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="nom_proprietaire",
            field=models.CharField(
                blank=True, help_text="Nom du propriétaire/gérant", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="original_title",
            field=models.CharField(
                blank=True, help_text="Titre original Google Maps", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="entreprise",
            index=models.Index(
                fields=["google_place_id"], name="enterprise__google__da9b5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entreprise",
            index=models.Index(
                fields=["latitude", "longitude"], name="enterprise__latitud_0cbb4b_idx"
            ),
        ),
    ]
