# Generated by Django 5.2.8 on 2025-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0002_entreprise_contacts_entreprise_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="enrichi_insee",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Données enrichies via API INSEE",
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="siren_temporaire",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="SIREN temporaire en attente d'enrichissement INSEE",
            ),
        ),
        migrations.AddIndex(
            model_name="entreprise",
            index=models.Index(
                fields=["siren_temporaire", "enrichi_insee"],
                name="enterprise__siren_t_749445_idx",
            ),
        ),
    ]
