# Generated by Django 5.2.8 on 2025-12-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise",
            "0003_entreprise_enrichi_insee_entreprise_siren_temporaire_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Customer ID (cus_xxx)",
                max_length=255,
            ),
        ),
    ]
