# Generated by Django 5.2.8 on 2026-01-24 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0004_add_stripe_customer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dirigeant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_dirigeant",
                    models.CharField(
                        choices=[
                            ("personne physique", "Personne physique"),
                            ("personne morale", "Personne morale"),
                        ],
                        default="personne physique",
                        help_text="Type de dirigeant",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, help_text="Nom de famille", max_length=255
                    ),
                ),
                (
                    "prenoms",
                    models.CharField(blank=True, help_text="Prénoms", max_length=255),
                ),
                (
                    "date_de_naissance",
                    models.CharField(
                        blank=True,
                        help_text="Date de naissance (YYYY-MM ou YYYY)",
                        max_length=10,
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        blank=True, help_text="Nationalité", max_length=100
                    ),
                ),
                (
                    "siren_dirigeant",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SIREN de la personne morale dirigeante",
                        max_length=9,
                    ),
                ),
                (
                    "denomination",
                    models.CharField(
                        blank=True,
                        help_text="Dénomination de la personne morale",
                        max_length=255,
                    ),
                ),
                (
                    "qualite",
                    models.CharField(
                        help_text="Qualité/fonction (Président, Gérant, etc.)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirigeant",
                "verbose_name_plural": "Dirigeants",
                "ordering": ["entreprise", "qualite", "nom"],
            },
        ),
        migrations.AddField(
            model_name="entreprise",
            name="enrichi_dirigeants",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Dirigeants enrichis via API Recherche Entreprises",
            ),
        ),
        migrations.AddIndex(
            model_name="entreprise",
            index=models.Index(
                fields=["enrichi_dirigeants"], name="enterprise__enrichi_a25197_idx"
            ),
        ),
        migrations.AddField(
            model_name="dirigeant",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dirigeants",
                to="enterprise.entreprise",
            ),
        ),
        migrations.AddIndex(
            model_name="dirigeant",
            index=models.Index(
                fields=["entreprise", "type_dirigeant"],
                name="enterprise__entrepr_d2d792_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dirigeant",
            index=models.Index(
                fields=["nom", "prenoms"], name="enterprise__nom_eba1ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dirigeant",
            index=models.Index(
                fields=["qualite"], name="enterprise__qualite_1dfbb7_idx"
            ),
        ),
    ]
