# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0005_add_dirigeants"),
    ]

    operations = [
        migrations.AddField(
            model_name="prolocalisation",
            name="faq",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="FAQ (15 Questions/Réponses) générées par IA - format: [{question, reponse}, ...]",
            ),
        ),
    ]
