# Generated by Django 5.2.8 on 2025-12-19 08:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VilleStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_villes", models.IntegerField()),
                ("total_departements", models.IntegerField()),
                ("total_regions", models.IntegerField()),
                ("population_totale", models.BigIntegerField()),
                ("population_moyenne", models.FloatField()),
            ],
            options={
                "verbose_name": "Statistiques Ville",
                "verbose_name_plural": "Statistiques Villes",
                "db_table": "ville_stats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "code_postal_principal",
                    models.CharField(db_index=True, max_length=5),
                ),
                (
                    "codes_postaux",
                    models.JSONField(
                        default=list, help_text="Liste des codes postaux de la ville"
                    ),
                ),
                ("departement", models.CharField(db_index=True, max_length=3)),
                ("region", models.CharField(db_index=True, max_length=100)),
                (
                    "lat",
                    models.FloatField(
                        help_text="Latitude",
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "lng",
                    models.FloatField(
                        help_text="Longitude",
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        default=0, help_text="Population (données INSEE)"
                    ),
                ),
                (
                    "texte_description_ia",
                    models.TextField(
                        blank=True,
                        help_text="Description de la ville générée par IA pour contexte local",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Meta description SEO (160 caractères max)",
                        max_length=160,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(
                        fields=["nom", "code_postal_principal"],
                        name="location_vi_nom_08d8b6_idx",
                    ),
                    models.Index(
                        fields=["departement", "region"],
                        name="location_vi_departe_866610_idx",
                    ),
                ],
            },
        ),
    ]
