# Generated by Django 5.2.8 on 2025-12-19 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("INACTIVE", "inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("ENTREPRISE", "Entreprises"),
                            ("VILLE", "Villes"),
                            ("CATEGORIE", "Catégories"),
                            ("SOUS_CATEGORIE", "Sous-catégories"),
                        ],
                        max_length=20,
                        verbose_name="Type d'import",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("PARTIAL", "Partiel (avec erreurs)"),
                            ("ERROR", "Erreur"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="imports/%Y/%m/%d/", verbose_name="Fichier"
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, verbose_name="Lignes totales"),
                ),
                (
                    "success_rows",
                    models.IntegerField(default=0, verbose_name="Lignes réussies"),
                ),
                (
                    "error_rows",
                    models.IntegerField(default=0, verbose_name="Lignes en erreur"),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des erreurs par ligne",
                        verbose_name="Détails des erreurs",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Démarré le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploadé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import de données",
                "verbose_name_plural": "Imports de données",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS core_status CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="Status",
                )
            ],
        ),
        migrations.AddIndex(
            model_name="importlog",
            index=models.Index(
                fields=["import_type", "status"], name="core_import_import__06037e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importlog",
            index=models.Index(
                fields=["-created_at"], name="core_import_created_618824_idx"
            ),
        ),
    ]
