# Generated by Django 5.2.8 on 2025-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_globalstatus_importlog_location_delete_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importlog",
            name="ai_generation_completed",
            field=models.BooleanField(
                default=False, verbose_name="Génération IA terminée"
            ),
        ),
        migrations.AddField(
            model_name="importlog",
            name="ai_generation_started",
            field=models.BooleanField(
                default=False, verbose_name="Génération IA démarrée"
            ),
        ),
        migrations.AddField(
            model_name="importlog",
            name="generate_ai_content",
            field=models.BooleanField(
                default=False,
                help_text="Générer automatiquement les descriptions IA après l'import",
                verbose_name="Générer contenu IA",
            ),
        ),
    ]
