#!/bin/bash

set -o errexit
set -o nounset


# Ensure dependencies are installed into /app/.venv (mounted volume)
uv sync --frozen


exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker -l INFO'
