# Generated by Django 5.2.8 on 2025-12-19 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsorisation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_debut", models.DateTimeField(db_index=True)),
                ("date_fin", models.DateTimeField(db_index=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Sponsorisation active"
                    ),
                ),
                (
                    "nb_impressions",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre d'impressions",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "nb_clicks",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de clics",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de l'abonnement Stripe",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "montant_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant mensuel en euros",
                        max_digits=10,
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("past_due", "Impayé"),
                            ("canceled", "Annulé"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "pro_localisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorisations",
                        to="enterprise.prolocalisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsorisation",
                "verbose_name_plural": "Sponsorisations",
                "ordering": ["-date_debut"],
                "indexes": [
                    models.Index(
                        fields=["pro_localisation", "is_active"],
                        name="sponsorisat_pro_loc_cbd77b_idx",
                    ),
                    models.Index(
                        fields=["date_debut", "date_fin"],
                        name="sponsorisat_date_de_988281_idx",
                    ),
                    models.Index(
                        fields=["statut_paiement", "is_active"],
                        name="sponsorisat_statut__bcb2e2_idx",
                    ),
                    models.Index(
                        fields=["nb_impressions"], name="sponsorisat_nb_impr_267e2e_idx"
                    ),
                ],
            },
        ),
    ]
